# .github/workflows/release.yaml

on:
  release:
    types: [created]
name: Build Release
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.30
        with:
          project_path: "src/browser-switcher"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: "386"
          goos: "linux"
          extra_files: "LICENSE"
          compress_assets: false

  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.30
        with:
          project_path: "src/browser-switcher"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: "amd64"
          goos: "linux"
          extra_files: "LICENSE"
          compress_assets: false

  release-linux-arm:
    name: release linux/arm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.30
        with:
          project_path: "src/browser-switcher"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: "arm"
          goos: "linux"
          extra_files: "LICENSE"
          compress_assets: false

  release-linux-arm64:
    name: release linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.30
        with:
          project_path: "src/browser-switcher"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: "arm64"
          goos: "linux"
          extra_files: "LICENSE"
          compress_assets: false
